// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.camiloporto.cloudfinance.model;

import br.com.camiloporto.cloudfinance.model.Profile;
import java.io.Serializable;

privileged aspect Profile_Roo_Serializable {
    
    declare parents: Profile implements Serializable;
    
    private static final long Profile.serialVersionUID = 1L;
    
}
