// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.camiloporto.cloudfinance.model;

import br.com.camiloporto.cloudfinance.model.UserRole;
import java.io.Serializable;

privileged aspect UserRole_Roo_Serializable {
    
    declare parents: UserRole implements Serializable;
    
    private static final long UserRole.serialVersionUID = 1L;
    
}
